name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd ./minigrep
        cargo build --verbose
    - name: Run tests
      run: |
        cd ./minigrep
        cargo test --verbose
